{{ if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" -}}
---
apiVersion: v1
data:
  password: YWRtaW4=
  username: YWRtaW4=
kind: Secret
metadata:
  name: {{ .Values.exporterMonitorCredentialName }}
  namespace: {{ .Release.Namespace }}
type: Opaque

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opensearch-clusters-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opensearch-operator.labels" . | nindent 4 }}
spec:
  endpoints:
  - basicAuth:
      password:
        key: password
        name: {{ .Values.exporterMonitorCredentialName }}
      username:
        key: username
        name: {{ .Values.exporterMonitorCredentialName }}
    path: /_prometheus/metrics
    port: http
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      opster.io/exporter-monitor: "yes"
{{ end }}